name: dp
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.1.31=h56e8100_0
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.6=h537db12_0
  - liblzma=5.6.4=h2466b09_0
  - libsqlite=3.49.1=h67fdade_1
  - libzlib=1.3.1=h2466b09_2
  - openssl=3.4.1=ha4e3fda_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.11.11=h3f84c4b_2_cpython
  - setuptools=75.8.2=pyhff2d567_0
  - tk=8.6.13=h5226925_1
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.3=h5fd82a7_24
  - vc14_runtime=14.42.34433=h6356254_24
  - wheel=0.45.1=pyhd8ed1ab_1
  - yaml=0.1.7=hfa6e2cd_1001
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - asttokens==3.0.0
      - attrs==25.1.0
      - blinker==1.9.0
      - blobfile==3.0.0
      - cairocffi==1.7.1
      - cairosvg==2.7.1
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.3.1
      - cssselect2==0.8.0
      - cycler==0.12.1
      - dash==2.18.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.2.1
      - defusedxml==0.7.1
      - easydict==1.13
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - flask==3.0.3
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grpcio==1.74.0
      - h5py==3.13.0
      - huggingface-hub==0.29.3
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - ipdb==0.13.13
      - ipython==9.0.1
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.8
      - labml==0.5.3
      - labml-helpers==0.4.89
      - lazy-loader==0.4
      - lightning-utilities==0.14.2
      - lxml==5.4.0
      - markdown==3.8.2
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - msvc-runtime==14.42.34433
      - multidict==6.2.0
      - narwhals==1.29.0
      - nbformat==5.10.4
      - ndjson==0.3.1
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==2.1.2
      - open3d==0.19.0
      - opencv-python==4.11.0.86
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pillow==11.0.0
      - platformdirs==4.3.6
      - plotly==6.0.0
      - progressbar==2.5
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - protobuf==6.30.2
      - psutil==7.0.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pycryptodomex==3.23.0
      - pygments==2.19.1
      - pymeshlab==2023.12.post2
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.5.1
      - pytz==2025.1
      - pywin32==308
      - pyyaml==6.0.2
      - rdp==0.8
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - retrying==1.3.4
      - rpds-py==0.23.1
      - ruptures==1.1.9
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - shapely==2.1.1
      - six==1.17.0
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - stack-data==0.6.3
      - svg-path==7.0
      - svgpathtools==1.6.1
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - tifffile==2025.6.11
      - timm==1.0.15
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - torch==2.6.0+cu118
      - torch-cluster==1.6.3
      - torch-geometric==2.6.1
      - torchaudio==2.6.0+cu118
      - torchmetrics==1.7.0
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.50.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.0.6
      - widgetsnbextension==4.0.13
      - yarl==1.18.3
      - zipp==3.21.0
prefix: C:\Users\ChengXi\anaconda3\envs\dp
